spring:
  datasource:
    url: jdbc:mysql://localhost:3306/povi?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 7241
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    restart:
      enabled: true
  output:
    ansi:
      enabled: always

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql.BasicBinder: trace